// Code generated by openapi-authz; DO NOT EDIT.
package authpolicy

type RouteKey struct {
	Method string
	Path   string
}

type AuthPolicy struct {
	RequireAuth bool
	Roles       []string
	Scopes      []string
}

// Policies is derived from OpenAPI security requirements; see openapi-authz docs.
var Policies = map[RouteKey]AuthPolicy{
	{Method: "GET", Path: "/admin"}: {RequireAuth: true, Roles: []string{"admin"}},
	{Method: "GET", Path: "/user"}:  {RequireAuth: true},
}
