// Code generated by openapi-authz; DO NOT EDIT.
package httproutes

type RouteKey struct {
	Method string
	Path   string
}

type AuthPolicy struct {
	RequireAuth bool
	Roles       []string
	Scopes      []string
}

// Policies is derived from OpenAPI security requirements; see openapi-authz docs.
var Policies = map[RouteKey]AuthPolicy{
	{Method: "DELETE", Path: "/admin"}: {RequireAuth: true, Roles: []string{"admin"}},
	{Method: "GET", Path: "/public"}:   {RequireAuth: false},
	{Method: "POST", Path: "/scoped"}:  {RequireAuth: true, Scopes: []string{"vegetable:write"}},
	{Method: "GET", Path: "/user"}:     {RequireAuth: true},
}
